### ISSUE TITLE
[Insight] Text files should end with a newline character - in web/index.php, line 6

### ISSUE THREAD

**Issue by kodemaan** [kodemaan/simplesilexmvc#1]
**[in web/index.php, line 6](https://github.com/kodemaan/simplesilexmvc/blob/aa1d499db93ba95971b0b86db81bea29f2c1a3bd/web/index.php#L6)**

> This file ends with no newline character. It won't render properly on a terminal, and it's considered a bad practice. Add a simple line feed as the last character to fix it.

```php
<?php
//Get all dependencies from app folder
require_once __DIR__.'/../app/app.php';

//Run silex application
$app->run();
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/b02add79-4e56-4c44-b685-fd14778b53ca/analyses/1)_

**Comment by Johnb21** [comment]
I hate you
